### ISSUE TITLE
#6 2023/03/10

### ISSUE THREAD

**Issue by hsh6449** [JBNU-JBIG/Paper-Review-Study#6]
1. 발표할 논문 + 요약 + 발표자료
2. 기타 공유할 것들

**Comment by hsh6449** [comment]
1. Visual prompting via image impainting
-[발표 자료](https://noble-stock-bf1.notion.site/Visual-Prompting-via-Image-Inpainting-2dccaa37e9214f738f769eb970bdf403)
-Summary : 기존 NLP의 prompting 기술을 image에 접목시켜서 general한 vision model을 만드는 시도를 함 

2. Reward Design with language model - [link](https://arxiv.org/pdf/2303.00001.pdf)

**Comment by ro-ko** [comment]
[발표자료](https://github.com/ro-ko/Paper_review/blob/main/Variational_inference.md)

Summary : let's master variational inference!

**Comment by hoyeon1234** [comment]
[논문 : Sequence to Sequence Learning with Neural Networks](https://arxiv.org/abs/1409.3215)
[발표자료](https://hoyeon1234.github.io/sin-hoyeon/posts/paper%20study/seq2seq/seq2seq.html)

요약 :  LSTM을 기반으로 sequence to sequence task에 적용하는 방법 제안

**Comment by baekingeol** [comment]
[논문](https://www.cs.cmu.edu/~rsalakhu/papers/oneshot1.pdf)

[3.10발표자료_Siamese_Neural_Network.pptx](https://github.com/JBNU-JBIG/Paper-Review-Study/files/10947985/3.10._Siamese_Neural_Network.pptx)
