### ISSUE TITLE
meeting 날짜 변경?

### ISSUE THREAD

**Issue by hsh6449** [JBNU-JBIG/Paper-Review-Study#8]
각자 선호하는 날짜나 좋은 방법 있으면 말해주세요

**Comment by jwk1121** [comment]
수요일을 제외한 평일 저녁이욧

**Comment by baekingeol** [comment]
화요일 (저녁7시~)이랑 수요일 10시이후, 금요일(저녁  7시~) 가능할 것 같습니다!

**Comment by hsh6449** [comment]
그러면 화요일 저녁에 하시는건 어떠신가요?!

**Comment by jwk1121** [comment]
저는 가능합니다

**Comment by hoyeon1234** [comment]
화요일 늦게 가능할거 같아요(10시반쯤?)

**Comment by hsh6449** [comment]
화요일 22:30으로 결정입니다
